### ISSUE TITLE
Slack link format's placeholder is not correct.

### ISSUE THREAD

**Issue by ritwickdey** [ywkim/slackstyler#1]
Currently.

```
input = "[description_text](http://example.com)"
output = <http://example.com>

input = "[description_text](http://example.com, 'this is title')"
output = <http://example.com | this is title>
```

But for both cases, it should be` <http://example.com | description_text>`

Reference: 
- https://github.com/jsarafajr/slackify-markdown/blob/43e4a38132c78cbe2693a7702a6f869f98c8ee64/__test__/slackify-markdown.test.js#L71
- https://www.markdownguide.org/basic-syntax/#links

**Comment by ritwickdey** [comment]
Could you please add the GitHub link to the PyPI repo https://pypi.org/project/slackstyler/?

And, thank you so much for making the helpful library. 💯 👍🏻

**Comment by BURG3R5** [comment]
@ywkim You should publish this change. The version on PyPI is not updated yet.

**Comment by ywkim** [comment]
> @ywkim You should publish this change. The version on PyPI is not updated yet.

@BURG3R5 Thanks for the heads up! I've just pushed version 0.0.3 to PyPI. It should be available for everyone now. Let me know if you spot any issues!
